package ui.jp;

import ui.lec.CorrectionOptionDialog;
import ui.AbstractTableModelImpl;
import cs.Guard;
import cs.loop.ArithmeticLoop;
import cs.loop.GeometricLoop;
import cs.loop.Loop;
import cs.loop.cg.ArithmeticCorrectionGenerator;
import cs.loop.cg.CorrectionGenerator;
import cs.loop.cg.GeometricCorrectionGenerator;
import cs.loop.ic.ArithmeticIterationCounter;
import cs.loop.ic.GeometricIterationCounter;
import cs.rmc.ArithmeticRecursiveMethodCall;
import cs.rmc.GeometricRecursiveMethodCall;
import cs.rmc.RecursiveMethodCall;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import maths.Relation;
import maths.is.ArithmeticInfiniteSequence;
import maths.is.GeometricInfiniteSequence;
import maths.is.InfiniteSequence;
import java.util.List;
import ui.lec.CorrectionRequestListener;

/**
 * A JPanel where the user can check for infinite recursion error.
 */
public class InfiniteRecursionPanel extends javax.swing.JPanel implements CorrectionRequestListener {

    private final Map<String, Integer> intInput_namesToVals;

    /**
     * Creates new form InfiniteRecursionPanel
     */
    public InfiniteRecursionPanel() {
        initComponents();
        intInput_namesToVals = new HashMap<>();

        for (JTextField textField : new JTextField[]{aTextField, bTextField, operandTextField}) {
            intInput_namesToVals.put(textField.getName(), null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        aTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RComboBox = new javax.swing.JComboBox<>();
        bTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        operatorComboBox = new javax.swing.JComboBox<>();
        operandTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        operandLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel1.setText("METHOD recursiveMethod(i)");

        aTextField.setName("a"); // NOI18N

        jLabel2.setText("IF i");

        RComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", "≤", ">", "≥", "≠", "=" }));

        bTextField.setName("b"); // NOI18N

        jLabel3.setText("THEN");

        jLabel4.setText("//don't recurse");

        operatorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "*" }));

        operandTextField.setName("operand"); // NOI18N

        jLabel5.setText("ELSE");

        checkButton.setText("Check");
        checkButton.setEnabled(false);

        jLabel6.setText("//call recursiveMethod(i");

        jLabel7.setText(")");

        jLabel8.setText("END_IF");

        jLabel9.setText("END_METHOD");

        jLabel10.setText("//at some point in program, call recursiveMethod(");

        jLabel11.setText(")");

        jLabel12.setText("b");

        jLabel13.setText("a");

        operandLabel.setText("d");

        jLabel15.setText("R");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel15)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel12))
                    .addComponent(checkButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))))
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(operatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(operandLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(operandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operandLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(operatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addComponent(jLabel13)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        (aTextField.getDocument()).addDocumentListener(new DocumentListenerImpl(aTextField));
        (bTextField.getDocument()).addDocumentListener(new DocumentListenerImpl(bTextField));
        operatorComboBox.addActionListener(new ComboBoxActionListenerImpl());
        (operandTextField.getDocument()).addDocumentListener(new DocumentListenerImpl(operandTextField));
        checkButton.addActionListener(new ButtonActionListenerImpl(this));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RComboBox;
    private javax.swing.JTextField aTextField;
    private javax.swing.JTextField bTextField;
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel operandLabel;
    private javax.swing.JTextField operandTextField;
    private javax.swing.JComboBox<String> operatorComboBox;
    // End of variables declaration//GEN-END:variables

    private boolean plusOperatorIsSelected() {
        return (operatorComboBox.getSelectedItem()).equals("+");
    }

    @Override
    public void correctionRequested(Map<String, Object> namesToValues) {
        intInput_namesToVals.put("a", (Integer) namesToValues.get("a"));
        intInput_namesToVals.put("b", (Integer) namesToValues.get("b"));
        String operandName = plusOperatorIsSelected() ? "d" : "r";
        intInput_namesToVals.put((operandName), (Integer) namesToValues.get(operandName));
        aTextField.setText(Integer.toString(intInput_namesToVals.get("a")));
        RComboBox.setSelectedItem(namesToValues.get("R"));
        bTextField.setText(Integer.toString(intInput_namesToVals.get("b")));
        operandTextField.setText(Integer.toString(intInput_namesToVals.get(operandName)));
    }

    private class ButtonActionListenerImpl implements ActionListener {

        InfiniteRecursionPanel panel;

        ButtonActionListenerImpl(InfiniteRecursionPanel panel) {
            this.panel = panel;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            Loop loop = getLoop();

            if (loop.terminates()) {
                JOptionPane.showMessageDialog(panel, "Recursion is finite (" + getIterationCount(loop) + " recursive call(s))");
            } else {
                (new CorrectionOptionDialog("Recursion is infinite", new AbstractTableModelImpl(getRowData_correctionTable(loop), getColumnData_correctionTable()), panel)).setVisible(true);
            }
        }

        Loop getLoop() {
            Guard baseCase = new Guard(Relation.values()[RComboBox.getSelectedIndex()], intInput_namesToVals.get("b"));
            int a = intInput_namesToVals.get("a"), operand = intInput_namesToVals.get("operand");
            RecursiveMethodCall call = plusOperatorIsSelected() ? new ArithmeticRecursiveMethodCall(new ArithmeticInfiniteSequence(a, operand), baseCase) : new GeometricRecursiveMethodCall(new GeometricInfiniteSequence(a, operand), baseCase);
            return call.toLoop();
        }

        int getIterationCount(Loop loop) {
            return (plusOperatorIsSelected() ? new ArithmeticIterationCounter((ArithmeticLoop) loop) : new GeometricIterationCounter((GeometricLoop) loop)).getCount();
        }

        Object[][] getRowData_correctionTable(Loop loop) {
            CorrectionGenerator generator = plusOperatorIsSelected() ? new ArithmeticCorrectionGenerator((ArithmeticLoop) loop) : new GeometricCorrectionGenerator((GeometricLoop) loop);
            List<Loop> corrections = generator.getCorrections();
            int numRows = corrections.size();
            Object[][] rowData = new Object[numRows][getColumnData_correctionTable().length];

            for (int row = 0; row < numRows; row++) {
                Loop correction = corrections.get(row);
                InfiniteSequence is = correction.getIS();
                Guard guard = correction.getGuard();
                rowData[row] = new Object[]{is.getA(), ((guard.getR()).getComplement()).toString(), guard.getB(), plusOperatorIsSelected() ? ((ArithmeticInfiniteSequence) is).getD() : ((GeometricInfiniteSequence) is).getR(), getIterationCount(correction)};
            }

            return rowData;
        }

        Object[] getColumnData_correctionTable() {
            return new Object[]{"a", "R", "b", (plusOperatorIsSelected() ? "d" : "r"), "Recursive calls"};
        }
    }

    private class ComboBoxActionListenerImpl implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            operandLabel.setText(plusOperatorIsSelected() ? "d" : "r");
        }
    }

    private class DocumentListenerImpl implements DocumentListener {

        JTextField textField;

        DocumentListenerImpl(JTextField textField) {
            this.textField = textField;
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            handleUpdate();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            handleUpdate();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            handleUpdate();
        }

        void handleUpdate() {
            Integer val;

            try {
                val = Integer.parseInt(textField.getText());
            } catch (NumberFormatException e) {
                val = null;
            }

            intInput_namesToVals.put(textField.getName(), val);
            checkButton.setEnabled(!intInput_namesToVals.containsValue(null));
        }
    }
}
